# Generated by Django 6.0.2 on 2026-02-20 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('siglas', models.CharField(max_length=20)),
                ('color_primario', models.CharField(default='#CC0000', max_length=7)),
                ('color_secundario', models.CharField(default='#FFFFFF', max_length=7)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partidos/')),
                ('ideologia', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('tema', models.CharField(choices=[('economia', 'Economía'), ('seguridad', 'Seguridad'), ('educacion', 'Educación'), ('salud', 'Salud'), ('medio_ambiente', 'Medio Ambiente'), ('corrupcion', 'Lucha Anticorrupción'), ('infraestructura', 'Infraestructura'), ('agricultura', 'Agricultura'), ('mujer', 'Género e Igualdad'), ('descentralizacion', 'Descentralización')], max_length=30)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Pregunta Quiz',
                'verbose_name_plural': 'Preguntas Quiz',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='candidatos/')),
                ('foto_url', models.URLField(blank=True, help_text='URL de foto si no hay archivo subido')),
                ('edad', models.IntegerField()),
                ('region', models.CharField(max_length=100)),
                ('profesion', models.CharField(max_length=200)),
                ('posicion_politica', models.CharField(choices=[('izquierda', 'Izquierda'), ('centro_izquierda', 'Centro-Izquierda'), ('centro', 'Centro'), ('centro_derecha', 'Centro-Derecha'), ('derecha', 'Derecha')], default='centro', max_length=20)),
                ('biografia', models.TextField()),
                ('experiencia', models.TextField()),
                ('lema', models.CharField(blank=True, max_length=300)),
                ('es_destacado', models.BooleanField(default=False)),
                ('score_economia', models.IntegerField(default=5, help_text='1=Estado, 10=Libre mercado')),
                ('score_seguridad', models.IntegerField(default=5, help_text='1=Derechos, 10=Mano dura')),
                ('score_medio_ambiente', models.IntegerField(default=5, help_text='1=Conservador, 10=Progresista')),
                ('score_educacion', models.IntegerField(default=5, help_text='1=Pública, 10=Privada')),
                ('score_salud', models.IntegerField(default=5, help_text='1=Universal, 10=Privada')),
                ('orden', models.IntegerField(default=0)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='candidatos.partido')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='OpcionQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=300)),
                ('valor', models.IntegerField(help_text='Valor en escala 1-10 que indica la posición política')),
                ('orden', models.IntegerField(default=0)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='candidatos.preguntaquiz')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Propuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(choices=[('economia', 'Economía'), ('seguridad', 'Seguridad'), ('educacion', 'Educación'), ('salud', 'Salud'), ('medio_ambiente', 'Medio Ambiente'), ('corrupcion', 'Lucha Anticorrupción'), ('infraestructura', 'Infraestructura'), ('agricultura', 'Agricultura'), ('mujer', 'Género e Igualdad'), ('descentralizacion', 'Descentralización')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(default='bi-star', max_length=50)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propuestas', to='candidatos.candidato')),
            ],
            options={
                'verbose_name': 'Propuesta',
                'verbose_name_plural': 'Propuestas',
                'ordering': ['tema'],
            },
        ),
    ]
