# Generated by Django 6.0.2 on 2026-02-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='antecedentes',
            field=models.TextField(blank=True, default='', help_text='Antecedentes legales o judiciales conocidos'),
        ),
    ]
