# Generated by Django 6.0.2 on 2026-02-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0002_candidato_antecedentes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propuesta',
            options={'ordering': ['prioridad', 'tema'], 'verbose_name': 'Propuesta', 'verbose_name_plural': 'Propuestas'},
        ),
        migrations.AddField(
            model_name='candidato',
            name='fuente_datos',
            field=models.CharField(default='Plan de Gobierno JNE 2026', max_length=200),
        ),
        migrations.AddField(
            model_name='candidato',
            name='link_plan_gobierno',
            field=models.URLField(blank=True, help_text='Link al PDF del plan de gobierno en JNE'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='posicion_politica_detalle',
            field=models.CharField(blank=True, help_text='Descripción detallada de la posición política', max_length=200),
        ),
        migrations.AddField(
            model_name='candidato',
            name='posicionamiento_issues',
            field=models.JSONField(blank=True, default=dict, help_text='Posición en temas clave como Asamblea Constituyente, Privatización, etc.'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='propuestas_destacadas',
            field=models.JSONField(blank=True, default=list, help_text='Lista de propuestas destacadas'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='resumen_propuestas',
            field=models.TextField(blank=True, help_text='Resumen general de las propuestas'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='ultima_actualizacion',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propuesta',
            name='prioridad',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10),
        ),
        migrations.AlterField(
            model_name='preguntaquiz',
            name='tema',
            field=models.CharField(choices=[('seguridad_ciudadana', 'Seguridad Ciudadana'), ('economia_empleo', 'Economía y Empleo'), ('salud', 'Salud'), ('educacion', 'Educación'), ('anticorrupcion', 'Lucha Anticorrupción'), ('infraestructura_agua_saneamiento', 'Infraestructura, Agua y Saneamiento'), ('medio_ambiente', 'Medio Ambiente'), ('reforma_estado', 'Reforma del Estado'), ('mypes_emprendimiento', 'MYPEs y Emprendimiento'), ('genero_inclusion', 'Género e Inclusión'), ('pensiones_adulto_mayor', 'Pensiones y Adulto Mayor')], max_length=50),
        ),
        migrations.AlterField(
            model_name='propuesta',
            name='tema',
            field=models.CharField(choices=[('seguridad_ciudadana', 'Seguridad Ciudadana'), ('economia_empleo', 'Economía y Empleo'), ('salud', 'Salud'), ('educacion', 'Educación'), ('anticorrupcion', 'Lucha Anticorrupción'), ('infraestructura_agua_saneamiento', 'Infraestructura, Agua y Saneamiento'), ('medio_ambiente', 'Medio Ambiente'), ('reforma_estado', 'Reforma del Estado'), ('mypes_emprendimiento', 'MYPEs y Emprendimiento'), ('genero_inclusion', 'Género e Inclusión'), ('pensiones_adulto_mayor', 'Pensiones y Adulto Mayor')], max_length=50),
        ),
        migrations.AlterField(
            model_name='propuesta',
            name='titulo',
            field=models.CharField(max_length=300),
        ),
    ]
