# Generated by Django 6.0.2 on 2026-02-21 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0004_visita'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('respuestas_json', models.JSONField(default=dict)),
                ('candidato_top', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidatos.candidato')),
            ],
            options={
                'verbose_name': 'Resultado de Quiz',
                'verbose_name_plural': 'Resultados de Quiz',
                'ordering': ['-fecha'],
            },
        ),
    ]
