# Generated by Django 6.0.2 on 2026-02-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0005_resultadoquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='score_corrupcion',
            field=models.IntegerField(default=5, help_text='1=Investigado/StatusQuo, 10=AnticorrupcionRadical'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='score_descentralizacion',
            field=models.IntegerField(default=5, help_text='1=Centralista, 10=Federalista/Regionalista'),
        ),
    ]
