# Generated by Django 6.0.2 on 2026-02-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0006_candidato_score_corrupcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encuestadora', models.CharField(help_text='Ej: IEP, CPI, Datum, etc.', max_length=120)),
                ('siglas', models.CharField(blank=True, help_text='Siglas de la encuestadora', max_length=20)),
                ('fecha_terreno', models.DateField(help_text='Fecha de realización del trabajo de campo')),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('resultados', models.JSONField(default=list, help_text='Lista de {"nombre": "Apellido Nombre", "porcentaje": 15.5}. Ordenar por porcentaje descendente.')),
                ('fuente_url', models.URLField(blank=True, help_text='Enlace a la publicación oficial')),
                ('nota', models.CharField(blank=True, help_text='Ej: Solo Lima, nacional, etc.', max_length=300)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Encuesta de intención de voto',
                'verbose_name_plural': 'Encuestas de intención de voto',
                'ordering': ['-fecha_terreno', '-fecha_publicacion', 'orden'],
            },
        ),
    ]
