# Generated by Django 6.0.2 on 2026-03-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0007_encuesta_intencion_voto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sugerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mejora', 'Mejora de la plataforma'), ('dato', 'Corrección de datos'), ('idea', 'Idea nueva'), ('otro', 'Otro')], default='mejora', max_length=20)),
                ('mensaje', models.TextField(help_text='Sugerencia o comentario del ciudadano')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sugerencia',
                'verbose_name_plural': 'Sugerencias',
                'ordering': ['-fecha'],
            },
        ),
    ]
