# Generated by Django 6.0.2 on 2026-03-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0008_sugerencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='fallecido',
            field=models.BooleanField(default=False, help_text='Marcar si el candidato ha fallecido'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='fecha_fallecimiento',
            field=models.DateField(blank=True, help_text='Fecha de fallecimiento (opcional)', null=True),
        ),
    ]
