# Generated by Django 6.0.2 on 2026-03-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0009_candidato_fallecido_candidato_fecha_fallecimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='info_financiera_estado',
            field=models.CharField(blank=True, help_text='Ej: DENTRO DE PLAZO, NO PRESENTO', max_length=50),
        ),
        migrations.AddField(
            model_name='candidato',
            name='info_financiera_fecha',
            field=models.DateField(blank=True, help_text='Fecha de presentación en ONPE', null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='info_financiera_gastos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gastos declarados (S/)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='info_financiera_ingresos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ingresos declarados (S/)', max_digits=12, null=True),
        ),
    ]
