# Generated by Django 6.0.2 on 2026-03-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0010_candidato_info_financiera_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='transparencia_onpe_presentaron',
            field=models.IntegerField(default=0, help_text='Número de candidatos que declararon cuentas dentro/fuera de plazo'),
        ),
        migrations.AddField(
            model_name='partido',
            name='transparencia_onpe_total_candidatos',
            field=models.IntegerField(default=0, help_text='Total de candidatos presentados en el registro ONPE'),
        ),
        migrations.AddField(
            model_name='partido',
            name='transparencia_porcentaje',
            field=models.FloatField(default=0.0, help_text='Porcentaje de cumplimiento (0 a 100)'),
        ),
        migrations.AddField(
            model_name='partido',
            name='transparencia_ultima_actualizacion',
            field=models.DateField(blank=True, help_text='Última vez que se actualizó con reporte ONPE', null=True),
        ),
    ]
