# Generated by Django 6.0.2 on 2026-03-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0011_partido_transparencia_onpe_presentaron_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='dni',
            field=models.CharField(blank=True, db_index=True, help_text='DNI del candidato', max_length=20, null=True, unique=True),
        ),
    ]
