# Generated by Django 6.0.2 on 2026-03-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0012_candidato_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='dni',
        ),
        migrations.AddField(
            model_name='candidato',
            name='rol_plancha',
            field=models.CharField(choices=[('presidente', 'Candidato/a a la Presidencia'), ('vp1', '1er Vicepresidente/a'), ('vp2', '2do Vicepresidente/a')], default='presidente', help_text='Rol dentro de la plancha presidencial', max_length=20),
        ),
    ]
