# Generated by Django 6.0.2 on 2026-03-17 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0013_add_rol_plancha'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='hoja_vida_jne',
            field=models.JSONField(blank=True, default=dict, help_text='Datos completos de la hoja de vida del JNE'),
        ),
    ]
