# Generated by Django 6.0.2 on 2026-03-17 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0014_add_hoja_vida_jne'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatoCongresal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=250)),
                ('genero', models.CharField(blank=True, choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino')], max_length=15)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('cargo', models.CharField(choices=[('DIPUTADO', 'Diputado'), ('SENADOR', 'Senador'), ('REPRESENTANTE DEL PARLAMENTO ANDINO', 'Parlamento Andino')], max_length=60)),
                ('organizacion_politica', models.CharField(max_length=200)),
                ('departamento', models.CharField(blank=True, max_length=80)),
                ('provincia', models.CharField(blank=True, max_length=80)),
                ('distrito', models.CharField(blank=True, max_length=80)),
                ('estado', models.CharField(choices=[('DENTRO DE PLAZO', 'Dentro de plazo'), ('FUERA DE PLAZO', 'Fuera de plazo'), ('NO PRESENTO', 'No presentó')], default='NO PRESENTO', max_length=30)),
                ('fecha_presentacion', models.CharField(blank=True, max_length=30)),
                ('ingresos', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gastos', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('entrega', models.CharField(blank=True, max_length=40)),
                ('partido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='congresales', to='candidatos.partido')),
            ],
            options={
                'verbose_name': 'Candidato Congresal',
                'verbose_name_plural': 'Candidatos Congresales',
                'ordering': ['organizacion_politica', 'cargo', 'nombre'],
                'indexes': [models.Index(fields=['cargo'], name='candidatos__cargo_60d0f7_idx'), models.Index(fields=['departamento'], name='candidatos__departa_18a975_idx'), models.Index(fields=['organizacion_politica'], name='candidatos__organiz_3a7860_idx'), models.Index(fields=['estado'], name='candidatos__estado_0f503b_idx')],
            },
        ),
    ]
