# Generated by AI assistant
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voto',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
    ]
